-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    X: in std_logic;
    Y: in std_logic;
    Z: out std_logic);
end main;

architecture Behavioral of main is
begin
  Z <= (X AND Y);
end Behavioral;
