/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module and_logic (
  input X,
  input Y,
  output Z
);
  assign Z = (X & Y);
endmodule
